//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Index.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Index.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
<<<<<<< HEAD
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap amongusimage1 {
            get {
                object obj = ResourceManager.GetObject("amongusimage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
>>>>>>> 8b1a1162fc34f25eaaa864a332174d5c350361d6
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CircularStd_Black {
            get {
                object obj = ResourceManager.GetObject("CircularStd_Black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CircularStd_Bold {
            get {
                object obj = ResourceManager.GetObject("CircularStd_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
<<<<<<< HEAD
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap astroneerimage2 {
            get {
                object obj = ResourceManager.GetObject("astroneerimage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
>>>>>>> 8b1a1162fc34f25eaaa864a332174d5c350361d6
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CircularStd_Book {
            get {
                object obj = ResourceManager.GetObject("CircularStd_Book", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CircularStd_Light {
            get {
                object obj = ResourceManager.GetObject("CircularStd_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CircularStd_Medium {
            get {
                object obj = ResourceManager.GetObject("CircularStd_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
<<<<<<< HEAD
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grandtheftautovimage1 {
            get {
                object obj = ResourceManager.GetObject("grandtheftautovimage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grandtheftautovimage2 {
            get {
                object obj = ResourceManager.GetObject("grandtheftautovimage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] library {
            get {
                object obj = ResourceManager.GetObject("library", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
>>>>>>> 8b1a1162fc34f25eaaa864a332174d5c350361d6
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phasmophobiaimage1 {
            get {
                object obj = ResourceManager.GetObject("phasmophobiaimage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phasmophobiaimage11 {
            get {
                object obj = ResourceManager.GetObject("phasmophobiaimage11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phasmophobiaimage2 {
            get {
                object obj = ResourceManager.GetObject("phasmophobiaimage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Product_Sans_Regular {
            get {
                object obj = ResourceManager.GetObject("Product_Sans_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
<<<<<<< HEAD
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rustimage1 {
            get {
                object obj = ResourceManager.GetObject("rustimage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rustimage2 {
            get {
                object obj = ResourceManager.GetObject("rustimage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
>>>>>>> 8b1a1162fc34f25eaaa864a332174d5c350361d6
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Segoe_Fluent_Icons {
            get {
                object obj = ResourceManager.GetObject("Segoe_Fluent_Icons", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
